image: Visual Studio 2017

environment:
  GIT_LFS_SKIP_SMUDGE: 1

install:
  - ps: Set-Culture de-DE

build_script:
  - mkdir build
  - cd build
  - cmake ..
  - cmake --build .

test_script:
  - ctest -C Debug

on_finish:
  # required for failed tests
  - appveyor PushArtifact tst_token_extractor-junit.xml
  - appveyor PushArtifact tst_data_file-junit.xml

artifacts:
  - path: 'build\Debug\*tt1*.exe'
    name: executables
